objects/Account_Plan__c.object
<CustomObject>
    <description>This object houses the Account Plan for a Digital Services specialist.  The Account Plan specifically pertains to the WebID object.  There may be multiple account plans across an account for a position if there is more than one webid, but there should only be one Account Plan per specialist per WebID.</description>
    <fields>
        <fullName>LMA_Analyst__c</fullName>
        <label>LMA Analyst</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>WebID__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>WebID</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>You must choose a WebID on the Account Plan’s associated Account.</errorMessage>
            <filterItems>
                <field>WebID__c.Account__c</field>
                <operation>equals</operation>
                <valueField>$Source.Account__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>WebID__c</referenceTo>
        <relationshipLabel>Account Plans</relationshipLabel>
        <relationshipName>Account_Plans</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Account Plan</label>
    <nameField>
        <displayFormat>AP-{00000}</displayFormat>
        <label>Account Plan ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/WebID__c.object
<CustomObject>
    <description>webIDs are the name given to website on an account</description>
    <fields>
        <fullName>LMA_Analyst2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>LMA Analyst2</label>
        <referenceTo>User</referenceTo>
        <relationshipName>WebIDs7</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>LMA_Analyst__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>LMA Analyst</label>
        <referenceTo>User</referenceTo>
        <relationshipName>WebIDs6</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>LMA_Strategist__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>LMA Strategist</label>
        <referenceTo>User</referenceTo>
        <relationshipName>WebIDs5</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>WebID</label>
    <nameField>
        <label>WebID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>WebIDs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/CB_UpdateAccountPlanFields.cls
public class CB_UpdateAccountPlanFields 
{
    public static void updateAccountPlan(map<ID, WebId__c> newMap, map<ID, WebId__c> oldMap)
    {
        //logic added for RQ-05402
        
        list<WebId__c> WebIDsChanged = new list<WebId__c>();
        set<string> fieldSet = new set<string>{ 'LMA_Analyst__c', 'LMA_Analyst2__c', 'LMA_Strategist__c' };
       
        for(webId__c w: newMap.values())
        {
            boolean filedsForCurrentWebIdChanged = false;
            filedsForCurrentWebIdChanged = ALL_UtilitiesLogic.compareNewAndOldTriggerValues(fieldSet, w, oldMap.get(w.ID));
            
            system.debug(filedsForCurrentWebIdChanged);
            
            if(filedsForCurrentWebIdChanged)
            {
                WebIDsChanged.add(w);
            }
        }
        
        if(!WebIDsChanged.isEmpty())
        {
            list<Account_Plan__c> APlist = new list<Account_Plan__c>([
                Select Id, WebId__c From Account_Plan__c 
                Where WebId__c 
                IN : WebIDsChanged
            ]);
            
            Database.update(APlist, false);
        }
    }
}