objects/Activity_Definition__c.object
<CustomObject>
    <description>Contains Offset Criteria, Offset days, Sequence and Terminal Activity associated with an Activity definition.</description>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sequence__c</fullName>
        <label>Sequence</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Project Activity Definition</label>
    <nameField>
        <displayFormat>AID-{00000000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Activity Definitions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Project_Activity__c.object
<CustomObject>
    <description>Contains Comments, Start, End Dates and relevant information for an Activity associated with a Milestone.</description>
    <fields>
        <fullName>Account__c</fullName>
        <formula>Milestone__r.Account__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Account</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Actual_End_Date_Final__c</fullName>
        <formula>IF(!ISBLANK(Actual_End_Date__c) &amp;&amp; (Total_Tasks__c - Total_Tasks_Closed__c == 0) &amp;&amp; Total_Tasks__c !=0, Actual_End_Date__c, null)</formula>
        <label>Actual End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Actual_End_Date__c</fullName>
        <label>Current Max Project Task End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Actual_Start_Date__c</fullName>
        <label>Actual Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Comments__c</fullName>
        <label>Comments</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Activity Description</label>
        <required>true</required>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Milestone__c</fullName>
        <label>Milestone</label>
        <referenceTo>Project_Milestone__c</referenceTo>
        <relationshipLabel>Activities</relationshipLabel>
        <relationshipName>Project_Activities</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Planned_End_Date__c</fullName>
        <label>Planned End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Planned_Start_Date__c</fullName>
        <label>Planned Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Process_Step__c</fullName>
        <description>Represents the Process Step associated with parent Project Milestone.</description>
        <formula>TEXT(Milestone__r.Process_Step__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Process Step</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Risk_Gauge_Color__c</fullName>
        <formula>IF( Status__c = &apos;At Risk&apos;, IMAGE(&quot;/servlet/servlet.FileDownload?file=015190000005uRy&quot;, &apos;At Risk&apos;),  
IF(Status__c = &apos;Caution&apos;, IMAGE(&quot;/servlet/servlet.FileDownload?file=015190000005uRz&quot;, &apos;Caution&apos;),IMAGE(&quot;/servlet/servlet.FileDownload?file=015190000005uRx&quot;, &apos;On Target&apos;)))</formula>
        <inlineHelpText>Red - At Risk
Yellow - Caution
Green - On Target</inlineHelpText>
        <label>Risk Gauge Color</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sequence__c</fullName>
        <label>Sequence</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Standard__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Standard</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <formula>IF( Total_Tasks__c == 0, &apos;Not Applicable&apos;,
IF( !ISBLANK(Actual_End_Date_Final__c) ,&apos;Complete&apos;, 
IF( ISBLANK(Planned_End_Date__c) ,&apos;On Target&apos;, 
IF( Duration_Buffer__c &lt;= 0,&apos;At Risk&apos;, 
IF( (Duration_Buffer__c &gt; 0) &amp;&amp; ((Duration_Buffer__c + MAX(DATETIMEVALUE(Planned_End_Date__c) - DATETIMEVALUE(TODAY()),0))/MAX(DATETIMEVALUE(Planned_End_Date__c) - DATETIMEVALUE(TODAY()),0) &lt;= 1.25),&apos;Caution&apos;, 
IF((Duration_Buffer__c &gt; 0) &amp;&amp; ((Duration_Buffer__c + MAX(DATETIMEVALUE(Planned_End_Date__c) - DATETIMEVALUE(TODAY()),0))/MAX(DATETIMEVALUE(Planned_End_Date__c) - DATETIMEVALUE(TODAY()),0) &gt; 1.25),&apos;On Target&apos;, 
null 
))))))</formula>
        <label>Status</label>
        <type>Text</type>
    </fields>
    <label>Project Activity</label>
    <nameField>
        <displayFormat>AI-{000000000}</displayFormat>
        <label>Activity ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Activities</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Project_Milestone__c.object
<CustomObject>
    <description>Contains Comments, Start, End Dates and relevant information for a Milestone associated with a SubProject.</description>
    <fields>
        <fullName>Account__c</fullName>
        <formula>Site__r.Account__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Account</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Actual_End_Date_Final__c</fullName>
        <formula>IF(!ISBLANK(Actual_End_Date__c) &amp;&amp; (Total_Activities__c - Total_Activities_Closed__c == 0) &amp;&amp; Total_Activities__c !=0, Actual_End_Date__c, null)</formula>
        <label>Actual End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Actual_End_Date__c</fullName>
        <label>Current Max Project Activity End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Actual_Start_Date__c</fullName>
        <label>Actual Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Comments__c</fullName>
        <label>Comments</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Milestone Description</label>
        <required>true</required>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>External_System_ID__c</fullName>
        <description>Field used to store IDs of external objects like LAO, NIS Mission etc as applicable for the Milestone</description>
        <label>External System ID</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>External_System_Name__c</fullName>
        <formula>External_System_New_Id__r.External_Entity_Name__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>External System Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Planned_End_Date__c</fullName>
        <label>Planned End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Planned_Start_Date__c</fullName>
        <label>Planned Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Process_Step__c</fullName>
        <description>Represents the step in the current 6 step process. The introduction of this attribute on the Milestone Definition object supports project milestone sorting, representing the primary sorting field in the View and Edit Milestone pages.</description>
        <label>Process Step</label>
        <picklist>
            <picklistValues>
                <fullName>01-Implementation Discovery</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>02-Project Mapping</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>03-Site Readiness</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>04-CDK GoLive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>05-Transition Meeting</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>06-Ongoing Training</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Risk_Gauge_Color__c</fullName>
        <formula>IF( Status__c = &apos;At Risk&apos;, IMAGE(&quot;/servlet/servlet.FileDownload?file=015190000005uRy&quot;, &apos;At Risk&apos;),  
IF(Status__c = &apos;Caution&apos;, IMAGE(&quot;/servlet/servlet.FileDownload?file=015190000005uRz&quot;, &apos;Caution&apos;),IMAGE(&quot;/servlet/servlet.FileDownload?file=015190000005uRx&quot;, &apos;On Target&apos;)))</formula>
        <inlineHelpText>Red - At Risk 
Yellow - Caution 
Green - On Target</inlineHelpText>
        <label>Risk Gauge Color</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Site__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Site</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>$Source.SubProject__c</field>
                <operation>equals</operation>
                <valueField>SubProjectSite__c.SubProject__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>SubProjectSite__c</referenceTo>
        <relationshipLabel>Project Milestones</relationshipLabel>
        <relationshipName>Project_Milestones</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sort_Sequence__c</fullName>
        <label>Sort Sequence</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Standard__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Standard</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <formula>IF( Total_Activities__c == 0,&apos;Not Applicable&apos;,
IF( !ISBLANK(Actual_End_Date_Final__c) ,&apos;Complete&apos;, 
IF( ISBLANK(Planned_End_Date__c) ,&apos;On Target&apos;, 
IF( Duration_Buffer__c &lt;= 0,&apos;At Risk&apos;, 
IF( (Duration_Buffer__c &gt; 0) &amp;&amp; ((Duration_Buffer__c + MAX(DATETIMEVALUE(Planned_End_Date__c) - DATETIMEVALUE(TODAY()),0))/MAX(DATETIMEVALUE(Planned_End_Date__c) - DATETIMEVALUE(TODAY()),0) &lt;= 1.25),&apos;Caution&apos;, 
IF((Duration_Buffer__c &gt; 0) &amp;&amp; ((Duration_Buffer__c + MAX(DATETIMEVALUE(Planned_End_Date__c) - DATETIMEVALUE(TODAY()),0))/MAX(DATETIMEVALUE(Planned_End_Date__c) - DATETIMEVALUE(TODAY()),0) &gt; 1.25),&apos;On Target&apos;, 
null 
))))))</formula>
        <label>Status</label>
        <type>Text</type>
    </fields>
    <label>Project Milestone</label>
    <nameField>
        <displayFormat>MID-{000000000}</displayFormat>
        <label>Milestone ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Milestones</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Project_Task__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <formula>Project_Activity__r.Account__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Account</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Actual_End_Date__c</fullName>
        <label>Actual End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Actual_Start_Date__c</fullName>
        <label>Actual Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Comments__c</fullName>
        <label>Comments</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Task Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Planned_End_Date__c</fullName>
        <label>Planned End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Planned_Start_Date__c</fullName>
        <label>Planned Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Project_Activity__c</fullName>
        <deleteConstraint>Cascade</deleteConstraint>
        <label>Project Activity</label>
        <referenceTo>Project_Activity__c</referenceTo>
        <relationshipLabel>Project Tasks</relationshipLabel>
        <relationshipName>Project_Tasks</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Standard__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Standard</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <formula>IF(Status_Not_Applicable__c = true,&apos;Not Applicable&apos;,
IF(!ISBLANK(Actual_End_Date__c),&apos;Complete&apos;,
IF(!ISBLANK(Actual_Start_Date__c) &amp;&amp; ISBLANK(Actual_End_Date__c),&apos;In Progress&apos;,
IF(!ISBLANK( CDK_Assignee__c ),&apos;Assigned&apos;,
IF(ISBLANK( CDK_Assignee__c ),&apos;Unassigned&apos;,
null
)))))</formula>
        <label>Status</label>
        <type>Text</type>
    </fields>
    <label>Project Task</label>
    <nameField>
        <displayFormat>TI-{000000000}</displayFormat>
        <label>Project Task Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Tasks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/SubProject__c.object
<CustomObject>
    <description>Subproject contains project information related to project type and/or product(s), as well as milestones, project logs and additional details;  rolls up to the Project.</description>
    <fields>
        <fullName>Comments__c</fullName>
        <description>Input scope details and notes (i.e. HOLD information, contacts w/o workspace, etc.)</description>
        <label>Comments</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>SubProject</label>
    <nameField>
        <displayFormat>SP-{00000000}</displayFormat>
        <label>SubProject ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SubProjects</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Task_Definition__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Project Task Definition</label>
    <nameField>
        <displayFormat>TID-{000000000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Task Definitions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/IMP_MiletoneView_V2_Controller.cls
global class IMP_MiletoneView_V2_Controller 
{  
    public static List<Project_Milestone__c> retrieveMilestoneRecords(String subId)
    {
        //Retrieve related milestones 
        String milestoneOrderQuery = IMP_Project_Utility.getOrderColumns(SObjectType.Project_Milestone__c.FieldSets.Milestone_Sort_Commons.getFields(), true);
        String activityOrderQuery = IMP_Project_Utility.getOrderColumns(SObjectType.Project_Activity__c.FieldSets.Activity_Sort_Commons.getFields(), true);
       
        String query = 'SELECT Actual_End_Date__c, Actual_End_Date_Final__c,Actual_Start_Date__c, Comments__c, Risk_Gauge_Color__c, Account__c ,' +
            'Process_Step__c,External_System_Name__c, Description__c, Planned_End_Date__c, Planned_Start_Date__c, ' +
            'Site__c, Status__c, Id, External_System_ID__c,Standard__c,Sort_Sequence__c,' +
            '(SELECT Activity_Definition__c,Actual_End_Date__c,Actual_End_Date_Final__c,Actual_Start_Date__c,CDK_Assignee__r.Name, External_ID__c,' +
            'CDK_Assignee_Role__c,Client_Assignee__r.Name,Department__c,Description__c,Display_on_PSR__c, Risk_Gauge_Color__c,' +
            'Planned_End_Date__c,Planned_Start_Date__c,Status__c,Comments__c,Standard__c,Sequence__c  FROM Project_Activities__r ' + activityOrderQuery + ') ' +
            'FROM Project_Milestone__c where SubProject__c =: subId ' + milestoneOrderQuery;
        
        return Database.query(query);
    }
    
    public static Map<Id, List<Project_Task__c>> retrieveTaskRecords(String subId)
    {
        //for unknown reason the objectId is becoming 18 char id, need to get only 15 char id
        Map<Id, List<Project_Task__c>> completeTaskMap = new Map<Id, List<Project_Task__c>> ();
     
        subId = subId.substring(0, 15);
     
        String taskOrderQuery = IMP_Project_Utility.getOrderColumns(SObjectType.Project_Task__c.FieldSets.Task_Sort_Commons.getFields(), true);
        
        String query = 'SELECT Project_Activity__c,Task_Definition__c,Actual_End_Date__c,Actual_Start_Date__c,CDK_Assignee__r.Name, External_ID__c, Expected_Time_Spent__c,' +
            'CDK_Assignee_Role__c,Client_Assignee__r.Name,Description__c,Display_on_PSR__c, Actual_Time_Spent__c, Reason__c,  Migration_Status__c, Reason_Missed_Planned_End_Date__c ,' +
            'Planned_End_Date__c,Planned_Start_Date__c,Status__c,Comments__c,Standard__c,Sequence__c  FROM Project_Task__c where SubProject_ID__c = : subId ' + taskOrderQuery;
        
        List<Project_Task__c> taskList = Database.query(query);
        
        //link the activity and the project task
        for (Project_Task__c tsk : taskList)
        {
            if (completeTaskMap.containsKey(tsk.Project_Activity__c))
            {
                //add the task in the existing activity
                //this automatically update the value in the completeTaskMap no need to re update the map
                List<Project_Task__c> tskList = completeTaskMap.get(tsk.Project_Activity__c);
                tskList.add(tsk);
            }
            else
            {
                List<Project_Task__c> tskList = new List<Project_Task__c> ();
                tskList.add(tsk);
                completeTaskMap.put(tsk.Project_Activity__c, tskList);
            }
        }
        
        return completeTaskMap;
    }
  
    @RemoteAction
    global static List<MilestoneWrapper> getSubProjectMilestones(String SubprojectId)
    {
        List<Project_Milestone__c> projectMilestones = retrieveMilestoneRecords(SubprojectId);
        Map<Id, List<Project_Task__c>> completeTaskMap = retrieveTaskRecords(SubprojectId);
        system.debug('projectMilestones' + projectMilestones.size());
        //populate the record in wrapper
        List<MilestoneWrapper> milestoneContentList = new List<MilestoneWrapper> ();
        for (Project_Milestone__c miles : projectMilestones)
        {
            MilestoneWrapper mWrapper = new MilestoneWrapper();
            mWrapper.obj = miles;
            //site have a different way to highlight in the field
            //it needs to be in a list of string
           
            mWrapper.toDelete = false;
            mWrapper.expandChild = false;
            mWrapper.section = 'Milestone';
            milestoneContentList.add(mWrapper);
            //populate the activity and add in the milestone
            if (miles.Project_Activities__r != null)
            {
                for (Project_Activity__c act : miles.Project_Activities__r)
                {
                    MilestoneWrapper aWrap = new MilestoneWrapper();
                    aWrap.obj = act;
                    aWrap.expandGrandChild = false;
                    aWrap.section = 'Activity';
                    aWrap.parentId = miles.Id;
                    milestoneContentList.add(aWrap);
                    //populate the task and add in the activity
                    if (completeTaskMap.containsKey(act.id))
                    {
                        List<Project_Task__c> taskList = completeTaskMap.get(act.id);
                        Boolean createHeader = true;
                        for (Project_Task__c t : taskList)
                        {
                            MilestoneWrapper tWrap = new MilestoneWrapper();
                            tWrap.obj = t;
                            tWrap.toDelete = false;
                            tWrap.hasError = false;
                            tWrap.section = 'Task';
                            tWrap.createHeader = createHeader;
                            tWrap.parentId = act.id;
                            milestoneContentList.add(tWrap);
                            createHeader = false;
                        }
                    }
                }
            }
        }
       
        return milestoneContentList;
    }
    
    global class MilestoneWrapper
    {
        public SObject obj { get; set; }       
        public Boolean expandChild { get; set; }     
        public Boolean expandGrandChild { get; set; }     
        public Boolean toDelete { get; set; }
        public Boolean hasError { get; set; }
        public Boolean createHeader { get; set; }
        public String section { get; set; }       
        public String parentId { get; set; }
    }
}