objects/Answer__c.object
<CustomObject>
    <description>Captures the response for a Discovery Question to the respective Workbook and associated with a Project.</description>
    <label>Discovery Answer</label>
    <nameField>
        <displayFormat>A-{0000000000}</displayFormat>
        <label>Answer Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Discovery Answers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Discovery_Answer_Workbook_Category__c.object
<CustomObject>
    <description>Junction object between Discovery Answer and Discovery Site Workbook category</description>
    <fields>
        <fullName>Answer_Completed__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Same value of Discovery Answer Any_Answer field.</description>
        <label>Answer Completed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Answer__c</fullName>
        <label>Answer</label>
        <referenceTo>Answer__c</referenceTo>
        <relationshipLabel>Discovery Answer Workbook Categories</relationshipLabel>
        <relationshipName>Discovery_Answer_Workbook_Categories</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Discovery Answer Workbook Category</label>
    <nameField>
        <displayFormat>DAWC-{0000000}</displayFormat>
        <label>Discovery Answer Workbook Category Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Discovery Answer Workbook Categories</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/IMP_UpdateAnsCompletedOfAnswerCategories.cls
public with sharing class IMP_UpdateAnsCompletedOfAnswerCategories 
{
	public static void updateAnsCompletedOnAnswerCategories(map<Id, boolean> anyAnswerValueMap)
	{
		list<Discovery_Answer_Workbook_Category__c> answerCategoriesToUpdate = new list<Discovery_Answer_Workbook_Category__c>();
		if(!anyAnswerValueMap.keySet().isEmpty())
		{
			list<Discovery_Answer_Workbook_Category__c> listToProcess= [
			select Answer_Completed__c, Answer__c from Discovery_Answer_Workbook_Category__c where
			Answer__c IN:anyAnswerValueMap.keySet()];
			for(Discovery_Answer_Workbook_Category__c dawc:listToProcess)
			{
                system.debug('--Discovery Answers-----'+anyAnswerValueMap.get(dawc.Answer__c));
				dawc.Answer_Completed__c = anyAnswerValueMap.get(dawc.Answer__c);
				answerCategoriesToUpdate.add(dawc);
			}
			if(!answerCategoriesToUpdate.isEmpty())
			{
				try { update answerCategoriesToUpdate; }
				catch (Exception e){System.debug(e);}
			}
			 
		}
		
		
	}

}