objects/EFD_Lasers__c.object
<CustomObject>
    <fields>
        <fullName>Installed_Date__c</fullName>
        <label>Installed Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Laser_Install__c</fullName>
        <label>Laser Install</label>
        <referenceTo>Laser_Install__c</referenceTo>
        <relationshipName>Non_EFD_Lasers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>EFD Lasers</label>
    <nameField>
        <displayFormat>EFL-{00000}</displayFormat>
        <label>EFD Lasers Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>EFD Lasers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Laser_Install__c.object
<CustomObject>
    <description>Installed Laser Information</description>
    <fields>
        <fullName>EFD_Lasers__c</fullName>
        <label># EFD Lasers</label>
        <precision>3</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>LIN_Status__c</fullName>
        <label>LIN Status</label>
        <picklist>
            <picklistValues>
                <fullName>Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Installed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>non_EFD_Lasers__c</fullName>
        <label># Non-EFD Lasers</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Laser Install</label>
    <nameField>
        <displayFormat>LIN - {00000}</displayFormat>
        <label>Laser Install</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Laser Installs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/DS_LaserInstall_Handler.cls
public class DS_LaserInstall_Handler 
{
    public static void QueryChildRecordsForUpdate(map<ID, Laser_Install__c> newMap, map<ID, Laser_Install__c> oldMap)
    {
        boolean GreenLight = false;
        
        set<ID> LiIDset = new set<ID>();
        
        if(newMap != null && !newMap.isEmpty())
        {
            for(Laser_Install__c li: newMap.values())
            {
                if(li.LIN_Status__c != null && li.LIN_Status__c.toLowerCase() == 'installed')
                {
                    GreenLight = true;
                    LiIDset.add(li.ID);
                }
            }
        }
        
        map<ID, Laser_Install__c> LaserInstallWithChildRecords;
        
        if(GreenLight && !LiIDset.isEmpty())
        {
            LaserInstallWithChildRecords = new map<ID, Laser_Install__c>([
                Select Id, Name, 
                      (Select Id, Name, Installed_Date__c 
                       From Non_EFD_Lasers__r)
                From Laser_Install__c 
                Where ID IN :LiIDset
            ]);
        }
        
        map<ID, EFD_Lasers__c> EfdUpdateMap = new map<ID, EFD_Lasers__c>();
        
        if(LaserInstallWithChildRecords != null && !LaserInstallWithChildRecords.isEmpty())
        {
            for(Laser_Install__c li: LaserInstallWithChildRecords.values())
            {
                if(LiIDset.contains(li.ID))
                {
                    list<EFD_Lasers__c> EFDLasers = li.getSobjects('Non_EFD_Lasers__r');
                    
                    if(EFDLasers != null && !EFDLasers.isEmpty())
                    {
                        for(EFD_Lasers__c efd: EFDLasers)
                        {
                            efd.Installed_Date__c = Date.Today();
                            EfdUpdateMap.put(efd.ID, efd);
                        }
                    }
                }
            }
        }
        
        if(EfdUpdateMap != null && !EfdUpdateMap.isEmpty()){ Update EfdUpdateMap.values();}
    }
}