objects/EFD_Lasers__c.object
<CustomObject>
    <fields>
        <fullName>Installed_Date__c</fullName>
        <label>Installed Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Laser_Install__c</fullName>
        <label>Laser Install</label>
        <referenceTo>Laser_Install__c</referenceTo>
        <relationshipName>Non_EFD_Lasers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>EFD Lasers</label>
    <nameField>
        <displayFormat>EFL-{00000}</displayFormat>
        <label>EFD Lasers Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>EFD Lasers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Laser_Install__c.object
<CustomObject>
    <description>Installed Laser Information</description>
    <fields>
        <fullName>EFD_Lasers__c</fullName>
        <label># EFD Lasers</label>
        <precision>3</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>EFD_Last_Downloaded__c</fullName>
        <label>EFD Last Downloaded</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>LIN_Status__c</fullName>
        <label>LIN Status</label>
        <picklist>
            <picklistValues>
                <fullName>Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Installed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Laser Install</label>
    <nameField>
        <displayFormat>LIN - {00000}</displayFormat>
        <label>Laser Install</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Laser Installs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/DS_LaserInstall_Test.cls
/*------------------------------------------------------------
Author:        Vishal Bandari
Description:   Test Class to Test DS_LaserInstall_Handler and ALL_Laser_Install Trigger
Created on:    2015-11-09.
Code Coverage: 100%
------------------------------------------------------------
History
2015-11-09    vishal.bandari@cdk.com        Created
------------------------------------------------------------*/
@Istest
public class DS_LaserInstall_Test 
{
    @testSetup
    static void setUptestData()
    {
        Laser_Install__c liObj = new Laser_Install__c();
        liObj.EFD_Last_Downloaded__c = Date.today();
        liObj.EFD_Lasers__c = 3.0;
        insert liObj;
        List<EFD_Lasers__c> efdList = new List<EFD_Lasers__c>();
        for(Integer i=0;i<3;i++)
        {
            EFD_Lasers__c efdObj = new EFD_Lasers__c();
            efdObj.Laser_Install__c = liobj.Id;
            efdList.add(efdObj);
        }
        insert efdList;
    }
    
    static testmethod void validateHandler()
    {
        Laser_Install__c liObj = [SELECT Id, LIN_Status__c FROM Laser_Install__c Order by CreatedDate desc LIMIT 1];
        liObj.LIN_Status__c = 'Installed';
        update liObj;
        List<EFD_Lasers__c> efdLaserList = [
            SELECT Id 
            FROM EFD_Lasers__c 
            WHERE Laser_Install__c =: liObj.Id
            AND Installed_Date__c =: Date.Today()
        ];
        System.assertEquals(efdLaserList.size(),3,'All EFD_Lasers__c are not updated');
    }
}